#!/bin/bash
# normal cpu stuff: allocate cpus, memory
#SBATCH --ntasks=1 --cpus-per-task=10 --mem=6000M
# we run on the gpu partition and we allocate 2 titanx gpus
#SBATCH -p gpu --gres=gpu:titanx:2
#We expect that our program should not run longer than 4 hours
#Note that a program will be killed once it exceeds this time!
SBATCH -p image2
SBATCH --time=00:10:00

#your script, in this case: write the hostname and the ids of the chosen gpus.
a00553.science.domain
echo $CUDA_VISIBLE_DEVICES
python3 count_reports.py 2019_06 /home/lkw918/sif /home/lkw918/sif/logs
